/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as InterviewShareableLinkImport } from './routes/interview.$shareableLink'
import { Route as AppAuthImport } from './routes/_app/_auth'
import { Route as AppAuthOnboardingLayoutImport } from './routes/_app/_auth/onboarding/_layout'
import { Route as AppAuthDashboardLayoutImport } from './routes/_app/_auth/dashboard/_layout'
import { Route as AppAuthDashboardLayoutIndexImport } from './routes/_app/_auth/dashboard/_layout.index'
import { Route as AppAuthOnboardingLayoutUsernameImport } from './routes/_app/_auth/onboarding/_layout.username'
import { Route as AppAuthDashboardLayoutSettingsImport } from './routes/_app/_auth/dashboard/_layout.settings'
import { Route as AppAuthDashboardLayoutCheckoutImport } from './routes/_app/_auth/dashboard/_layout.checkout'
import { Route as AppAuthAgentsCreateLayoutImport } from './routes/_app/_auth/agents/create/_layout'
import { Route as AppAuthAgentsAgentIdAttemptsImport } from './routes/_app/_auth/agents/$agentId.attempts'
import { Route as AppAuthDashboardLayoutSettingsIndexImport } from './routes/_app/_auth/dashboard/_layout.settings.index'
import { Route as AppAuthDashboardLayoutSettingsBillingImport } from './routes/_app/_auth/dashboard/_layout.settings.billing'
import { Route as AppAuthAgentsCreateLayoutQuestionsImport } from './routes/_app/_auth/agents/create/_layout.questions'
import { Route as AppAuthAgentsCreateLayoutKnowledgeSourcesImport } from './routes/_app/_auth/agents/create/_layout.knowledge-sources'
import { Route as AppAuthAgentsCreateLayoutBehaviorImport } from './routes/_app/_auth/agents/create/_layout.behavior'
import { Route as AppAuthAgentsAgentIdAttemptsAttemptIdImport } from './routes/_app/_auth/agents/$agentId.attempts.$attemptId'

// Create Virtual Routes

const AppAuthOnboardingImport = createFileRoute('/_app/_auth/onboarding')()
const AppAuthDashboardImport = createFileRoute('/_app/_auth/dashboard')()
const AppAuthAgentsCreateImport = createFileRoute('/_app/_auth/agents/create')()

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const InterviewShareableLinkRoute = InterviewShareableLinkImport.update({
  path: '/interview/$shareableLink',
  getParentRoute: () => rootRoute,
} as any)

const AppAuthRoute = AppAuthImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthOnboardingRoute = AppAuthOnboardingImport.update({
  path: '/onboarding',
  getParentRoute: () => AppAuthRoute,
} as any)

const AppAuthDashboardRoute = AppAuthDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AppAuthRoute,
} as any)

const AppAuthAgentsCreateRoute = AppAuthAgentsCreateImport.update({
  path: '/agents/create',
  getParentRoute: () => AppAuthRoute,
} as any)

const AppAuthOnboardingLayoutRoute = AppAuthOnboardingLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AppAuthOnboardingRoute,
} as any)

const AppAuthDashboardLayoutRoute = AppAuthDashboardLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AppAuthDashboardRoute,
} as any)

const AppAuthDashboardLayoutIndexRoute =
  AppAuthDashboardLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthOnboardingLayoutUsernameRoute =
  AppAuthOnboardingLayoutUsernameImport.update({
    path: '/username',
    getParentRoute: () => AppAuthOnboardingLayoutRoute,
  } as any)

const AppAuthDashboardLayoutSettingsRoute =
  AppAuthDashboardLayoutSettingsImport.update({
    path: '/settings',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutCheckoutRoute =
  AppAuthDashboardLayoutCheckoutImport.update({
    path: '/checkout',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthAgentsCreateLayoutRoute = AppAuthAgentsCreateLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AppAuthAgentsCreateRoute,
} as any)

const AppAuthAgentsAgentIdAttemptsRoute =
  AppAuthAgentsAgentIdAttemptsImport.update({
    path: '/agents/$agentId/attempts',
    getParentRoute: () => AppAuthRoute,
  } as any)

const AppAuthDashboardLayoutSettingsIndexRoute =
  AppAuthDashboardLayoutSettingsIndexImport.update({
    path: '/',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

const AppAuthDashboardLayoutSettingsBillingRoute =
  AppAuthDashboardLayoutSettingsBillingImport.update({
    path: '/billing',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

const AppAuthAgentsCreateLayoutQuestionsRoute =
  AppAuthAgentsCreateLayoutQuestionsImport.update({
    path: '/questions',
    getParentRoute: () => AppAuthAgentsCreateLayoutRoute,
  } as any)

const AppAuthAgentsCreateLayoutKnowledgeSourcesRoute =
  AppAuthAgentsCreateLayoutKnowledgeSourcesImport.update({
    path: '/knowledge-sources',
    getParentRoute: () => AppAuthAgentsCreateLayoutRoute,
  } as any)

const AppAuthAgentsCreateLayoutBehaviorRoute =
  AppAuthAgentsCreateLayoutBehaviorImport.update({
    path: '/behavior',
    getParentRoute: () => AppAuthAgentsCreateLayoutRoute,
  } as any)

const AppAuthAgentsAgentIdAttemptsAttemptIdRoute =
  AppAuthAgentsAgentIdAttemptsAttemptIdImport.update({
    path: '/$attemptId',
    getParentRoute: () => AppAuthAgentsAgentIdAttemptsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppAuthImport
      parentRoute: typeof AppImport
    }
    '/interview/$shareableLink': {
      id: '/interview/$shareableLink'
      path: '/interview/$shareableLink'
      fullPath: '/interview/$shareableLink'
      preLoaderRoute: typeof InterviewShareableLinkImport
      parentRoute: typeof rootRoute
    }
    '/_app/_auth/dashboard': {
      id: '/_app/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthDashboardImport
      parentRoute: typeof AppAuthImport
    }
    '/_app/_auth/dashboard/_layout': {
      id: '/_app/_auth/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthDashboardLayoutImport
      parentRoute: typeof AppAuthDashboardRoute
    }
    '/_app/_auth/onboarding': {
      id: '/_app/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppAuthOnboardingImport
      parentRoute: typeof AppAuthImport
    }
    '/_app/_auth/onboarding/_layout': {
      id: '/_app/_auth/onboarding/_layout'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppAuthOnboardingLayoutImport
      parentRoute: typeof AppAuthOnboardingRoute
    }
    '/_app/_auth/agents/$agentId/attempts': {
      id: '/_app/_auth/agents/$agentId/attempts'
      path: '/agents/$agentId/attempts'
      fullPath: '/agents/$agentId/attempts'
      preLoaderRoute: typeof AppAuthAgentsAgentIdAttemptsImport
      parentRoute: typeof AppAuthImport
    }
    '/_app/_auth/agents/create': {
      id: '/_app/_auth/agents/create'
      path: '/agents/create'
      fullPath: '/agents/create'
      preLoaderRoute: typeof AppAuthAgentsCreateImport
      parentRoute: typeof AppAuthImport
    }
    '/_app/_auth/agents/create/_layout': {
      id: '/_app/_auth/agents/create/_layout'
      path: '/agents/create'
      fullPath: '/agents/create'
      preLoaderRoute: typeof AppAuthAgentsCreateLayoutImport
      parentRoute: typeof AppAuthAgentsCreateRoute
    }
    '/_app/_auth/dashboard/_layout/checkout': {
      id: '/_app/_auth/dashboard/_layout/checkout'
      path: '/checkout'
      fullPath: '/dashboard/checkout'
      preLoaderRoute: typeof AppAuthDashboardLayoutCheckoutImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/settings': {
      id: '/_app/_auth/dashboard/_layout/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/onboarding/_layout/username': {
      id: '/_app/_auth/onboarding/_layout/username'
      path: '/username'
      fullPath: '/onboarding/username'
      preLoaderRoute: typeof AppAuthOnboardingLayoutUsernameImport
      parentRoute: typeof AppAuthOnboardingLayoutImport
    }
    '/_app/_auth/dashboard/_layout/': {
      id: '/_app/_auth/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppAuthDashboardLayoutIndexImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/agents/$agentId/attempts/$attemptId': {
      id: '/_app/_auth/agents/$agentId/attempts/$attemptId'
      path: '/$attemptId'
      fullPath: '/agents/$agentId/attempts/$attemptId'
      preLoaderRoute: typeof AppAuthAgentsAgentIdAttemptsAttemptIdImport
      parentRoute: typeof AppAuthAgentsAgentIdAttemptsImport
    }
    '/_app/_auth/agents/create/_layout/behavior': {
      id: '/_app/_auth/agents/create/_layout/behavior'
      path: '/behavior'
      fullPath: '/agents/create/behavior'
      preLoaderRoute: typeof AppAuthAgentsCreateLayoutBehaviorImport
      parentRoute: typeof AppAuthAgentsCreateLayoutImport
    }
    '/_app/_auth/agents/create/_layout/knowledge-sources': {
      id: '/_app/_auth/agents/create/_layout/knowledge-sources'
      path: '/knowledge-sources'
      fullPath: '/agents/create/knowledge-sources'
      preLoaderRoute: typeof AppAuthAgentsCreateLayoutKnowledgeSourcesImport
      parentRoute: typeof AppAuthAgentsCreateLayoutImport
    }
    '/_app/_auth/agents/create/_layout/questions': {
      id: '/_app/_auth/agents/create/_layout/questions'
      path: '/questions'
      fullPath: '/agents/create/questions'
      preLoaderRoute: typeof AppAuthAgentsCreateLayoutQuestionsImport
      parentRoute: typeof AppAuthAgentsCreateLayoutImport
    }
    '/_app/_auth/dashboard/_layout/settings/billing': {
      id: '/_app/_auth/dashboard/_layout/settings/billing'
      path: '/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsBillingImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsImport
    }
    '/_app/_auth/dashboard/_layout/settings/': {
      id: '/_app/_auth/dashboard/_layout/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsIndexImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AppRoute: AppRoute.addChildren({
    AppAuthRoute: AppAuthRoute.addChildren({
      AppAuthDashboardRoute: AppAuthDashboardRoute.addChildren({
        AppAuthDashboardLayoutRoute: AppAuthDashboardLayoutRoute.addChildren({
          AppAuthDashboardLayoutCheckoutRoute,
          AppAuthDashboardLayoutSettingsRoute:
            AppAuthDashboardLayoutSettingsRoute.addChildren({
              AppAuthDashboardLayoutSettingsBillingRoute,
              AppAuthDashboardLayoutSettingsIndexRoute,
            }),
          AppAuthDashboardLayoutIndexRoute,
        }),
      }),
      AppAuthOnboardingRoute: AppAuthOnboardingRoute.addChildren({
        AppAuthOnboardingLayoutRoute: AppAuthOnboardingLayoutRoute.addChildren({
          AppAuthOnboardingLayoutUsernameRoute,
        }),
      }),
      AppAuthAgentsAgentIdAttemptsRoute:
        AppAuthAgentsAgentIdAttemptsRoute.addChildren({
          AppAuthAgentsAgentIdAttemptsAttemptIdRoute,
        }),
      AppAuthAgentsCreateRoute: AppAuthAgentsCreateRoute.addChildren({
        AppAuthAgentsCreateLayoutRoute:
          AppAuthAgentsCreateLayoutRoute.addChildren({
            AppAuthAgentsCreateLayoutBehaviorRoute,
            AppAuthAgentsCreateLayoutKnowledgeSourcesRoute,
            AppAuthAgentsCreateLayoutQuestionsRoute,
          }),
      }),
    }),
  }),
  InterviewShareableLinkRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/interview/$shareableLink"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/_auth"
      ]
    },
    "/_app/_auth": {
      "filePath": "_app/_auth.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_auth/dashboard",
        "/_app/_auth/onboarding",
        "/_app/_auth/agents/$agentId/attempts",
        "/_app/_auth/agents/create"
      ]
    },
    "/interview/$shareableLink": {
      "filePath": "interview.$shareableLink.tsx"
    },
    "/_app/_auth/dashboard": {
      "filePath": "_app/_auth/dashboard",
      "parent": "/_app/_auth",
      "children": [
        "/_app/_auth/dashboard/_layout"
      ]
    },
    "/_app/_auth/dashboard/_layout": {
      "filePath": "_app/_auth/dashboard/_layout.tsx",
      "parent": "/_app/_auth/dashboard",
      "children": [
        "/_app/_auth/dashboard/_layout/checkout",
        "/_app/_auth/dashboard/_layout/settings",
        "/_app/_auth/dashboard/_layout/"
      ]
    },
    "/_app/_auth/onboarding": {
      "filePath": "_app/_auth/onboarding",
      "parent": "/_app/_auth",
      "children": [
        "/_app/_auth/onboarding/_layout"
      ]
    },
    "/_app/_auth/onboarding/_layout": {
      "filePath": "_app/_auth/onboarding/_layout.tsx",
      "parent": "/_app/_auth/onboarding",
      "children": [
        "/_app/_auth/onboarding/_layout/username"
      ]
    },
    "/_app/_auth/agents/$agentId/attempts": {
      "filePath": "_app/_auth/agents/$agentId.attempts.tsx",
      "parent": "/_app/_auth",
      "children": [
        "/_app/_auth/agents/$agentId/attempts/$attemptId"
      ]
    },
    "/_app/_auth/agents/create": {
      "filePath": "_app/_auth/agents/create",
      "parent": "/_app/_auth",
      "children": [
        "/_app/_auth/agents/create/_layout"
      ]
    },
    "/_app/_auth/agents/create/_layout": {
      "filePath": "_app/_auth/agents/create/_layout.tsx",
      "parent": "/_app/_auth/agents/create",
      "children": [
        "/_app/_auth/agents/create/_layout/behavior",
        "/_app/_auth/agents/create/_layout/knowledge-sources",
        "/_app/_auth/agents/create/_layout/questions"
      ]
    },
    "/_app/_auth/dashboard/_layout/checkout": {
      "filePath": "_app/_auth/dashboard/_layout.checkout.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/settings": {
      "filePath": "_app/_auth/dashboard/_layout.settings.tsx",
      "parent": "/_app/_auth/dashboard/_layout",
      "children": [
        "/_app/_auth/dashboard/_layout/settings/billing",
        "/_app/_auth/dashboard/_layout/settings/"
      ]
    },
    "/_app/_auth/onboarding/_layout/username": {
      "filePath": "_app/_auth/onboarding/_layout.username.tsx",
      "parent": "/_app/_auth/onboarding/_layout"
    },
    "/_app/_auth/dashboard/_layout/": {
      "filePath": "_app/_auth/dashboard/_layout.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/agents/$agentId/attempts/$attemptId": {
      "filePath": "_app/_auth/agents/$agentId.attempts.$attemptId.tsx",
      "parent": "/_app/_auth/agents/$agentId/attempts"
    },
    "/_app/_auth/agents/create/_layout/behavior": {
      "filePath": "_app/_auth/agents/create/_layout.behavior.tsx",
      "parent": "/_app/_auth/agents/create/_layout"
    },
    "/_app/_auth/agents/create/_layout/knowledge-sources": {
      "filePath": "_app/_auth/agents/create/_layout.knowledge-sources.tsx",
      "parent": "/_app/_auth/agents/create/_layout"
    },
    "/_app/_auth/agents/create/_layout/questions": {
      "filePath": "_app/_auth/agents/create/_layout.questions.tsx",
      "parent": "/_app/_auth/agents/create/_layout"
    },
    "/_app/_auth/dashboard/_layout/settings/billing": {
      "filePath": "_app/_auth/dashboard/_layout.settings.billing.tsx",
      "parent": "/_app/_auth/dashboard/_layout/settings"
    },
    "/_app/_auth/dashboard/_layout/settings/": {
      "filePath": "_app/_auth/dashboard/_layout.settings.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout/settings"
    }
  }
}
ROUTE_MANIFEST_END */
